// GENERATED by scripts/ingest/world-regions.mjs from https://download.geofabrik.de/index-v1.json on 2026-09-24.
// Do not edit by hand: re-run the script.
//
// Every Geofabrik file the load may be asked to read, which is every file
// GeofabrikMap.regionAt (lib/discovery/geofabrik.ts) could pick for some
// point on Earth: never a continent, an overlay such as US Northeast, a
// country Geofabrik splits into pieces, or North Korea. A region not listed
// here is refused before anything is downloaded.

/** Region path → the countries it holds (ISO 3166-1 alpha-2). */
export const GEOFABRIK_REGIONS: Readonly<Record<string, readonly string[]>> = {
  "africa/algeria": [
    "DZ"
  ],
  "africa/angola": [
    "AO"
  ],
  "africa/benin": [
    "BJ"
  ],
  "africa/botswana": [
    "BW"
  ],
  "africa/burkina-faso": [
    "BF"
  ],
  "africa/burundi": [
    "BI"
  ],
  "africa/cameroon": [
    "CM"
  ],
  "africa/cape-verde": [
    "CV"
  ],
  "africa/central-african-republic": [
    "CF"
  ],
  "africa/chad": [
    "TD"
  ],
  "africa/congo-brazzaville": [
    "CG"
  ],
  "africa/congo-democratic-republic": [
    "CD"
  ],
  "africa/djibouti": [
    "DJ"
  ],
  "africa/egypt": [
    "EG"
  ],
  "africa/equatorial-guinea": [
    "GQ"
  ],
  "africa/eritrea": [
    "ER"
  ],
  "africa/ethiopia": [
    "ET"
  ],
  "africa/gabon": [
    "GA"
  ],
  "africa/ghana": [
    "GH"
  ],
  "africa/guinea": [
    "GN"
  ],
  "africa/guinea-bissau": [
    "GW"
  ],
  "africa/ivory-coast": [
    "CI"
  ],
  "africa/kenya": [
    "KE"
  ],
  "africa/lesotho": [
    "LS"
  ],
  "africa/liberia": [
    "LR"
  ],
  "africa/libya": [
    "LY"
  ],
  "africa/madagascar": [
    "MG"
  ],
  "africa/malawi": [
    "MW"
  ],
  "africa/mali": [
    "ML"
  ],
  "africa/mauritania": [
    "MR"
  ],
  "africa/mauritius": [
    "MU"
  ],
  "africa/morocco": [
    "MA"
  ],
  "africa/mozambique": [
    "MZ"
  ],
  "africa/namibia": [
    "NA"
  ],
  "africa/niger": [
    "NE"
  ],
  "africa/nigeria": [
    "NG"
  ],
  "africa/rwanda": [
    "RW"
  ],
  "africa/saint-helena-ascension-and-tristan-da-cunha": [
    "SH"
  ],
  "africa/sao-tome-and-principe": [
    "ST"
  ],
  "africa/senegal-and-gambia": [
    "SN",
    "GM"
  ],
  "africa/seychelles": [
    "SC"
  ],
  "africa/sierra-leone": [
    "SL"
  ],
  "africa/somalia": [
    "SO"
  ],
  "africa/south-africa": [
    "ZA"
  ],
  "africa/south-sudan": [
    "SS"
  ],
  "africa/sudan": [
    "SD"
  ],
  "africa/swaziland": [
    "SZ"
  ],
  "africa/tanzania": [
    "TZ"
  ],
  "africa/togo": [
    "TG"
  ],
  "africa/tunisia": [
    "TN"
  ],
  "africa/uganda": [
    "UG"
  ],
  "africa/zambia": [
    "ZM"
  ],
  "africa/zimbabwe": [
    "ZW"
  ],
  "antarctica": [
    "AQ"
  ],
  "asia/afghanistan": [
    "AF"
  ],
  "asia/armenia": [
    "AM"
  ],
  "asia/azerbaijan": [
    "AZ"
  ],
  "asia/bangladesh": [
    "BD"
  ],
  "asia/bhutan": [
    "BT"
  ],
  "asia/cambodia": [
    "KH"
  ],
  "asia/china/anhui": [
    "CN"
  ],
  "asia/china/beijing": [
    "CN"
  ],
  "asia/china/chongqing": [
    "CN"
  ],
  "asia/china/fujian": [
    "CN"
  ],
  "asia/china/gansu": [
    "CN"
  ],
  "asia/china/guangdong": [
    "CN"
  ],
  "asia/china/guangxi": [
    "CN"
  ],
  "asia/china/guizhou": [
    "CN"
  ],
  "asia/china/hainan": [
    "CN"
  ],
  "asia/china/hebei": [
    "CN"
  ],
  "asia/china/heilongjiang": [
    "CN"
  ],
  "asia/china/henan": [
    "CN"
  ],
  "asia/china/hong-kong": [
    "HK"
  ],
  "asia/china/hubei": [
    "CN"
  ],
  "asia/china/hunan": [
    "CN"
  ],
  "asia/china/inner-mongolia": [
    "CN"
  ],
  "asia/china/jiangsu": [
    "CN"
  ],
  "asia/china/jiangxi": [
    "CN"
  ],
  "asia/china/jilin": [
    "CN"
  ],
  "asia/china/liaoning": [
    "CN"
  ],
  "asia/china/macau": [
    "MO"
  ],
  "asia/china/ningxia": [
    "CN"
  ],
  "asia/china/qinghai": [
    "CN"
  ],
  "asia/china/shaanxi": [
    "CN"
  ],
  "asia/china/shandong": [
    "CN"
  ],
  "asia/china/shanghai": [
    "CN"
  ],
  "asia/china/shanxi": [
    "CN"
  ],
  "asia/china/sichuan": [
    "CN"
  ],
  "asia/china/tianjin": [
    "CN"
  ],
  "asia/china/tibet": [
    "CN"
  ],
  "asia/china/xinjiang": [
    "CN"
  ],
  "asia/china/yunnan": [
    "CN"
  ],
  "asia/china/zhejiang": [
    "CN"
  ],
  "asia/east-timor": [
    "TL"
  ],
  "asia/gcc-states": [
    "SA",
    "QA",
    "AE",
    "OM",
    "BH",
    "KW"
  ],
  "asia/india/central-zone": [
    "IN"
  ],
  "asia/india/eastern-zone": [
    "IN"
  ],
  "asia/india/north-eastern-zone": [
    "IN"
  ],
  "asia/india/northern-zone": [
    "IN"
  ],
  "asia/india/southern-zone": [
    "IN"
  ],
  "asia/india/western-zone": [
    "IN"
  ],
  "asia/indonesia/java": [
    "ID"
  ],
  "asia/indonesia/kalimantan": [
    "ID"
  ],
  "asia/indonesia/maluku": [
    "ID"
  ],
  "asia/indonesia/nusa-tenggara": [
    "ID"
  ],
  "asia/indonesia/papua": [
    "ID"
  ],
  "asia/indonesia/sulawesi": [
    "ID"
  ],
  "asia/indonesia/sumatra": [
    "ID"
  ],
  "asia/iran": [
    "IR"
  ],
  "asia/iraq": [
    "IQ"
  ],
  "asia/israel-and-palestine": [
    "PS",
    "IL"
  ],
  "asia/japan/chubu": [
    "JP"
  ],
  "asia/japan/chugoku": [
    "JP"
  ],
  "asia/japan/hokkaido": [
    "JP"
  ],
  "asia/japan/kansai": [
    "JP"
  ],
  "asia/japan/kanto": [
    "JP"
  ],
  "asia/japan/kyushu": [
    "JP"
  ],
  "asia/japan/shikoku": [
    "JP"
  ],
  "asia/japan/tohoku": [
    "JP"
  ],
  "asia/jordan": [
    "JO"
  ],
  "asia/kazakhstan": [
    "KZ"
  ],
  "asia/kyrgyzstan": [
    "KG"
  ],
  "asia/laos": [
    "LA"
  ],
  "asia/lebanon": [
    "LB"
  ],
  "asia/malaysia-singapore-brunei": [
    "MY",
    "SG",
    "BN"
  ],
  "asia/maldives": [
    "MV"
  ],
  "asia/mongolia": [
    "MN"
  ],
  "asia/myanmar": [
    "MM"
  ],
  "asia/nepal": [
    "NP"
  ],
  "asia/pakistan": [
    "PK"
  ],
  "asia/philippines": [
    "PH"
  ],
  "asia/south-korea": [
    "KR"
  ],
  "asia/sri-lanka": [
    "LK"
  ],
  "asia/syria": [
    "SY"
  ],
  "asia/taiwan": [
    "TW"
  ],
  "asia/tajikistan": [
    "TJ"
  ],
  "asia/thailand": [
    "TH"
  ],
  "asia/turkmenistan": [
    "TM"
  ],
  "asia/uzbekistan": [
    "UZ"
  ],
  "asia/vietnam": [
    "VN"
  ],
  "asia/yemen": [
    "YE"
  ],
  "australia-oceania/american-oceania": [
    "AS",
    "GU",
    "MP",
    "UM"
  ],
  "australia-oceania/australia/act": [
    "AU"
  ],
  "australia-oceania/australia/ashmore-cartier": [
    "AU"
  ],
  "australia-oceania/australia/christmas-island": [
    "AU"
  ],
  "australia-oceania/australia/cocos-islands": [
    "AU"
  ],
  "australia-oceania/australia/coral-sea-islands": [
    "AU"
  ],
  "australia-oceania/australia/heard-mcdonald": [
    "AU"
  ],
  "australia-oceania/australia/new-south-wales": [
    "AU"
  ],
  "australia-oceania/australia/norfolk-island": [
    "AU"
  ],
  "australia-oceania/australia/northern-territory": [
    "AU"
  ],
  "australia-oceania/australia/queensland": [
    "AU"
  ],
  "australia-oceania/australia/south-australia": [
    "AU"
  ],
  "australia-oceania/australia/tasmania": [
    "AU"
  ],
  "australia-oceania/australia/victoria": [
    "AU"
  ],
  "australia-oceania/australia/western-australia": [
    "AU"
  ],
  "australia-oceania/cook-islands": [
    "CK"
  ],
  "australia-oceania/fiji": [
    "FJ"
  ],
  "australia-oceania/ile-de-clipperton": [
    "FR"
  ],
  "australia-oceania/kiribati": [
    "KI"
  ],
  "australia-oceania/marshall-islands": [
    "MH"
  ],
  "australia-oceania/micronesia": [
    "FM"
  ],
  "australia-oceania/nauru": [
    "NR"
  ],
  "australia-oceania/new-caledonia": [
    "NC"
  ],
  "australia-oceania/new-zealand": [
    "NZ"
  ],
  "australia-oceania/niue": [
    "NU"
  ],
  "australia-oceania/palau": [
    "PW"
  ],
  "australia-oceania/papua-new-guinea": [
    "PG"
  ],
  "australia-oceania/pitcairn-islands": [
    "PN"
  ],
  "australia-oceania/polynesie-francaise": [
    "PF"
  ],
  "australia-oceania/samoa": [
    "WS"
  ],
  "australia-oceania/solomon-islands": [
    "SB"
  ],
  "australia-oceania/tokelau": [
    "TK"
  ],
  "australia-oceania/tonga": [
    "TO"
  ],
  "australia-oceania/tuvalu": [
    "TV"
  ],
  "australia-oceania/vanuatu": [
    "VU"
  ],
  "australia-oceania/wallis-et-futuna": [
    "WF"
  ],
  "central-america/bahamas": [
    "BS"
  ],
  "central-america/belize": [
    "BZ"
  ],
  "central-america/costa-rica": [
    "CR"
  ],
  "central-america/cuba": [
    "CU"
  ],
  "central-america/el-salvador": [
    "SV"
  ],
  "central-america/guatemala": [
    "GT"
  ],
  "central-america/haiti-and-domrep": [
    "HT",
    "DO"
  ],
  "central-america/honduras": [
    "HN"
  ],
  "central-america/jamaica": [
    "JM"
  ],
  "central-america/nicaragua": [
    "NI"
  ],
  "central-america/panama": [
    "PA"
  ],
  "europe/albania": [
    "AL"
  ],
  "europe/andorra": [
    "AD"
  ],
  "europe/austria": [
    "AT"
  ],
  "europe/belarus": [
    "BY"
  ],
  "europe/belgium": [
    "BE"
  ],
  "europe/bosnia-herzegovina": [
    "BA"
  ],
  "europe/bulgaria": [
    "BG"
  ],
  "europe/croatia": [
    "HR"
  ],
  "europe/cyprus": [
    "CY"
  ],
  "europe/czech-republic/jihocesky": [
    "CZ"
  ],
  "europe/czech-republic/jihomoravsky": [
    "CZ"
  ],
  "europe/czech-republic/karlovarsky": [
    "CZ"
  ],
  "europe/czech-republic/kralovehradecky": [
    "CZ"
  ],
  "europe/czech-republic/liberecky": [
    "CZ"
  ],
  "europe/czech-republic/moravskoslezky": [
    "CZ"
  ],
  "europe/czech-republic/olomoucky": [
    "CZ"
  ],
  "europe/czech-republic/pardubicky": [
    "CZ"
  ],
  "europe/czech-republic/plzensky": [
    "CZ"
  ],
  "europe/czech-republic/praha": [
    "CZ"
  ],
  "europe/czech-republic/stredocesky": [
    "CZ"
  ],
  "europe/czech-republic/ustecky": [
    "CZ"
  ],
  "europe/czech-republic/vysocina": [
    "CZ"
  ],
  "europe/czech-republic/zlinsky": [
    "CZ"
  ],
  "europe/denmark": [
    "DK"
  ],
  "europe/estonia": [
    "EE"
  ],
  "europe/faroe-islands": [
    "FO"
  ],
  "europe/finland": [
    "FI"
  ],
  "europe/france/alsace": [
    "FR"
  ],
  "europe/france/aquitaine": [
    "FR"
  ],
  "europe/france/auvergne": [
    "FR"
  ],
  "europe/france/basse-normandie": [
    "FR"
  ],
  "europe/france/bourgogne": [
    "FR"
  ],
  "europe/france/bretagne": [
    "FR"
  ],
  "europe/france/centre": [
    "FR"
  ],
  "europe/france/champagne-ardenne": [
    "FR"
  ],
  "europe/france/corse": [
    "FR"
  ],
  "europe/france/franche-comte": [
    "FR"
  ],
  "europe/france/guadeloupe": [
    "FR"
  ],
  "europe/france/guyane": [
    "GF"
  ],
  "europe/france/haute-normandie": [
    "FR"
  ],
  "europe/france/ile-de-france": [
    "FR"
  ],
  "europe/france/languedoc-roussillon": [
    "FR"
  ],
  "europe/france/limousin": [
    "FR"
  ],
  "europe/france/lorraine": [
    "FR"
  ],
  "europe/france/martinique": [
    "FR"
  ],
  "europe/france/mayotte": [
    "FR"
  ],
  "europe/france/midi-pyrenees": [
    "FR"
  ],
  "europe/france/nord-pas-de-calais": [
    "FR"
  ],
  "europe/france/pays-de-la-loire": [
    "FR"
  ],
  "europe/france/picardie": [
    "FR"
  ],
  "europe/france/poitou-charentes": [
    "FR"
  ],
  "europe/france/provence-alpes-cote-d-azur": [
    "FR"
  ],
  "europe/france/reunion": [
    "FR"
  ],
  "europe/france/rhone-alpes": [
    "FR"
  ],
  "europe/georgia": [
    "GE"
  ],
  "europe/germany/baden-wuerttemberg/freiburg-regbez": [
    "DE"
  ],
  "europe/germany/baden-wuerttemberg/karlsruhe-regbez": [
    "DE"
  ],
  "europe/germany/baden-wuerttemberg/stuttgart-regbez": [
    "DE"
  ],
  "europe/germany/baden-wuerttemberg/tuebingen-regbez": [
    "DE"
  ],
  "europe/germany/bayern/mittelfranken": [
    "DE"
  ],
  "europe/germany/bayern/niederbayern": [
    "DE"
  ],
  "europe/germany/bayern/oberbayern": [
    "DE"
  ],
  "europe/germany/bayern/oberfranken": [
    "DE"
  ],
  "europe/germany/bayern/oberpfalz": [
    "DE"
  ],
  "europe/germany/bayern/schwaben": [
    "DE"
  ],
  "europe/germany/bayern/unterfranken": [
    "DE"
  ],
  "europe/germany/berlin": [
    "DE"
  ],
  "europe/germany/brandenburg": [
    "DE"
  ],
  "europe/germany/bremen": [
    "DE"
  ],
  "europe/germany/hamburg": [
    "DE"
  ],
  "europe/germany/hessen": [
    "DE"
  ],
  "europe/germany/mecklenburg-vorpommern": [
    "DE"
  ],
  "europe/germany/niedersachsen": [
    "DE"
  ],
  "europe/germany/nordrhein-westfalen/arnsberg-regbez": [
    "DE"
  ],
  "europe/germany/nordrhein-westfalen/detmold-regbez": [
    "DE"
  ],
  "europe/germany/nordrhein-westfalen/duesseldorf-regbez": [
    "DE"
  ],
  "europe/germany/nordrhein-westfalen/koeln-regbez": [
    "DE"
  ],
  "europe/germany/nordrhein-westfalen/muenster-regbez": [
    "DE"
  ],
  "europe/germany/rheinland-pfalz": [
    "DE"
  ],
  "europe/germany/saarland": [
    "DE"
  ],
  "europe/germany/sachsen": [
    "DE"
  ],
  "europe/germany/sachsen-anhalt": [
    "DE"
  ],
  "europe/germany/schleswig-holstein": [
    "DE"
  ],
  "europe/germany/thueringen": [
    "DE"
  ],
  "europe/greece": [
    "GR"
  ],
  "europe/hungary": [
    "HU"
  ],
  "europe/iceland": [
    "IS"
  ],
  "europe/ireland-and-northern-ireland": [
    "IE",
    "GB"
  ],
  "europe/italy/centro": [
    "IT"
  ],
  "europe/italy/isole": [
    "IT"
  ],
  "europe/italy/nord-est": [
    "IT"
  ],
  "europe/italy/nord-ovest": [
    "IT"
  ],
  "europe/italy/sud": [
    "IT"
  ],
  "europe/latvia": [
    "LV"
  ],
  "europe/liechtenstein": [
    "LI"
  ],
  "europe/lithuania": [
    "LT"
  ],
  "europe/luxembourg": [
    "LU"
  ],
  "europe/macedonia": [
    "MK"
  ],
  "europe/malta": [
    "MT"
  ],
  "europe/moldova": [
    "MD"
  ],
  "europe/monaco": [
    "MC"
  ],
  "europe/montenegro": [
    "ME"
  ],
  "europe/netherlands/drenthe": [
    "NL"
  ],
  "europe/netherlands/flevoland": [
    "NL"
  ],
  "europe/netherlands/friesland": [
    "NL"
  ],
  "europe/netherlands/gelderland": [
    "NL"
  ],
  "europe/netherlands/groningen": [
    "NL"
  ],
  "europe/netherlands/limburg": [
    "NL"
  ],
  "europe/netherlands/noord-brabant": [
    "NL"
  ],
  "europe/netherlands/noord-holland": [
    "NL"
  ],
  "europe/netherlands/overijssel": [
    "NL"
  ],
  "europe/netherlands/utrecht": [
    "NL"
  ],
  "europe/netherlands/zeeland": [
    "NL"
  ],
  "europe/netherlands/zuid-holland": [
    "NL"
  ],
  "europe/norway/nord-norge": [
    "NO"
  ],
  "europe/norway/ostlandet": [
    "NO"
  ],
  "europe/norway/sorlandet": [
    "NO"
  ],
  "europe/norway/svalbard-janmayen": [
    "NO"
  ],
  "europe/norway/trondelag": [
    "NO"
  ],
  "europe/norway/vestlandet": [
    "NO"
  ],
  "europe/poland/dolnoslaskie": [
    "PL"
  ],
  "europe/poland/kujawsko-pomorskie": [
    "PL"
  ],
  "europe/poland/lodzkie": [
    "PL"
  ],
  "europe/poland/lubelskie": [
    "PL"
  ],
  "europe/poland/lubuskie": [
    "PL"
  ],
  "europe/poland/malopolskie": [
    "PL"
  ],
  "europe/poland/mazowieckie": [
    "PL"
  ],
  "europe/poland/opolskie": [
    "PL"
  ],
  "europe/poland/podkarpackie": [
    "PL"
  ],
  "europe/poland/podlaskie": [
    "PL"
  ],
  "europe/poland/pomorskie": [
    "PL"
  ],
  "europe/poland/slaskie": [
    "PL"
  ],
  "europe/poland/swietokrzyskie": [
    "PL"
  ],
  "europe/poland/warminsko-mazurskie": [
    "PL"
  ],
  "europe/poland/wielkopolskie": [
    "PL"
  ],
  "europe/poland/zachodniopomorskie": [
    "PL"
  ],
  "europe/portugal": [
    "PT"
  ],
  "europe/romania": [
    "RO"
  ],
  "europe/serbia": [
    "RS"
  ],
  "europe/slovakia": [
    "SK"
  ],
  "europe/slovenia": [
    "SI"
  ],
  "europe/spain/andalucia": [
    "ES"
  ],
  "europe/spain/aragon": [
    "ES"
  ],
  "europe/spain/asturias": [
    "ES"
  ],
  "europe/spain/cantabria": [
    "ES"
  ],
  "europe/spain/castilla-la-mancha": [
    "ES"
  ],
  "europe/spain/castilla-y-leon": [
    "ES"
  ],
  "europe/spain/cataluna": [
    "ES"
  ],
  "europe/spain/ceuta": [
    "ES"
  ],
  "europe/spain/extremadura": [
    "ES"
  ],
  "europe/spain/galicia": [
    "ES"
  ],
  "europe/spain/islas-baleares": [
    "ES"
  ],
  "europe/spain/la-rioja": [
    "ES"
  ],
  "europe/spain/madrid": [
    "ES"
  ],
  "europe/spain/melilla": [
    "ES"
  ],
  "europe/spain/murcia": [
    "ES"
  ],
  "europe/spain/navarra": [
    "ES"
  ],
  "europe/spain/pais-vasco": [
    "ES"
  ],
  "europe/spain/valencia": [
    "ES"
  ],
  "europe/sweden": [
    "SE"
  ],
  "europe/switzerland": [
    "CH"
  ],
  "europe/turkey": [
    "TR"
  ],
  "europe/ukraine": [
    "UA"
  ],
  "europe/united-kingdom/bermuda": [
    "GB"
  ],
  "europe/united-kingdom/england": [
    "GB"
  ],
  "europe/united-kingdom/falklands": [
    "GB"
  ],
  "europe/united-kingdom/scotland": [
    "GB"
  ],
  "europe/united-kingdom/wales": [
    "GB"
  ],
  "north-america/canada/alberta": [
    "CA"
  ],
  "north-america/canada/british-columbia/interior-admreg": [
    "CA"
  ],
  "north-america/canada/british-columbia/island-admreg": [
    "CA"
  ],
  "north-america/canada/british-columbia/kootenay-admreg": [
    "CA"
  ],
  "north-america/canada/british-columbia/north-admreg": [
    "CA"
  ],
  "north-america/canada/british-columbia/okanagan-admreg": [
    "CA"
  ],
  "north-america/canada/british-columbia/southcoast-admreg": [
    "CA"
  ],
  "north-america/canada/manitoba": [
    "CA"
  ],
  "north-america/canada/new-brunswick": [
    "CA"
  ],
  "north-america/canada/newfoundland-and-labrador": [
    "CA"
  ],
  "north-america/canada/northwest-territories": [
    "CA"
  ],
  "north-america/canada/nova-scotia": [
    "CA"
  ],
  "north-america/canada/nunavut/kitikmeot": [
    "CA"
  ],
  "north-america/canada/nunavut/kivalliq": [
    "CA"
  ],
  "north-america/canada/nunavut/qikiqtaaluk": [
    "CA"
  ],
  "north-america/canada/ontario": [
    "CA"
  ],
  "north-america/canada/prince-edward-island": [
    "CA"
  ],
  "north-america/canada/quebec": [
    "CA"
  ],
  "north-america/canada/saskatchewan": [
    "CA"
  ],
  "north-america/canada/yukon": [
    "CA"
  ],
  "north-america/greenland": [
    "GL"
  ],
  "north-america/mexico": [
    "MX"
  ],
  "north-america/us/alabama": [
    "US"
  ],
  "north-america/us/alaska": [
    "US"
  ],
  "north-america/us/arizona": [
    "US"
  ],
  "north-america/us/arkansas": [
    "US"
  ],
  "north-america/us/california": [
    "US"
  ],
  "north-america/us/colorado": [
    "US"
  ],
  "north-america/us/connecticut": [
    "US"
  ],
  "north-america/us/delaware": [
    "US"
  ],
  "north-america/us/district-of-columbia": [
    "US"
  ],
  "north-america/us/florida": [
    "US"
  ],
  "north-america/us/georgia": [
    "US"
  ],
  "north-america/us/hawaii": [
    "US"
  ],
  "north-america/us/idaho": [
    "US"
  ],
  "north-america/us/illinois": [
    "US"
  ],
  "north-america/us/indiana": [
    "US"
  ],
  "north-america/us/iowa": [
    "US"
  ],
  "north-america/us/kansas": [
    "US"
  ],
  "north-america/us/kentucky": [
    "US"
  ],
  "north-america/us/louisiana": [
    "US"
  ],
  "north-america/us/maine": [
    "US"
  ],
  "north-america/us/maryland": [
    "US"
  ],
  "north-america/us/massachusetts": [
    "US"
  ],
  "north-america/us/michigan": [
    "US"
  ],
  "north-america/us/minnesota": [
    "US"
  ],
  "north-america/us/mississippi": [
    "US"
  ],
  "north-america/us/missouri": [
    "US"
  ],
  "north-america/us/montana": [
    "US"
  ],
  "north-america/us/nebraska": [
    "US"
  ],
  "north-america/us/nevada": [
    "US"
  ],
  "north-america/us/new-hampshire": [
    "US"
  ],
  "north-america/us/new-jersey": [
    "US"
  ],
  "north-america/us/new-mexico": [
    "US"
  ],
  "north-america/us/new-york": [
    "US"
  ],
  "north-america/us/north-carolina": [
    "US"
  ],
  "north-america/us/north-dakota": [
    "US"
  ],
  "north-america/us/ohio": [
    "US"
  ],
  "north-america/us/oklahoma": [
    "US"
  ],
  "north-america/us/oregon": [
    "US"
  ],
  "north-america/us/pennsylvania": [
    "US"
  ],
  "north-america/us/puerto-rico": [
    "PR"
  ],
  "north-america/us/rhode-island": [
    "US"
  ],
  "north-america/us/south-carolina": [
    "US"
  ],
  "north-america/us/south-dakota": [
    "US"
  ],
  "north-america/us/tennessee": [
    "US"
  ],
  "north-america/us/texas": [
    "US"
  ],
  "north-america/us/us-virgin-islands": [
    "VI"
  ],
  "north-america/us/utah": [
    "US"
  ],
  "north-america/us/vermont": [
    "US"
  ],
  "north-america/us/virginia": [
    "US"
  ],
  "north-america/us/washington": [
    "US"
  ],
  "north-america/us/west-virginia": [
    "US"
  ],
  "north-america/us/wisconsin": [
    "US"
  ],
  "north-america/us/wyoming": [
    "US"
  ],
  "russia/central-fed-district": [
    "RU"
  ],
  "russia/crimean-fed-district": [
    "RU"
  ],
  "russia/far-eastern-fed-district": [
    "RU"
  ],
  "russia/kaliningrad": [
    "RU"
  ],
  "russia/north-caucasus-fed-district": [
    "RU"
  ],
  "russia/northwestern-fed-district": [
    "RU"
  ],
  "russia/siberian-fed-district": [
    "RU"
  ],
  "russia/south-fed-district": [
    "RU"
  ],
  "russia/ural-fed-district": [
    "RU"
  ],
  "russia/volga-fed-district": [
    "RU"
  ],
  "south-america/argentina": [
    "AR"
  ],
  "south-america/bolivia": [
    "BO"
  ],
  "south-america/brazil/centro-oeste": [
    "BR"
  ],
  "south-america/brazil/nordeste": [
    "BR"
  ],
  "south-america/brazil/norte": [
    "BR"
  ],
  "south-america/brazil/sudeste": [
    "BR"
  ],
  "south-america/brazil/sul": [
    "BR"
  ],
  "south-america/chile": [
    "CL"
  ],
  "south-america/colombia": [
    "CO"
  ],
  "south-america/ecuador": [
    "EC"
  ],
  "south-america/guyana": [
    "GY"
  ],
  "south-america/paraguay": [
    "PY"
  ],
  "south-america/peru": [
    "PE"
  ],
  "south-america/suriname": [
    "SR"
  ],
  "south-america/uruguay": [
    "UY"
  ],
  "south-america/venezuela": [
    "VE"
  ]
};

/**
 * Megabytes of each base file (every US state and territory, the UK's
 * nations, Mexico, the Bahamas and the world list's files) when this was
 * written. The workflow gives a region time by its size; a region not
 * listed (one a plan added) gets the longest.
 */
export const REGION_MB: Readonly<Record<string, number>> = {
  "africa/egypt": 179,
  "asia/china/beijing": 37,
  "asia/china/guangdong": 173,
  "asia/china/hebei": 108,
  "asia/china/hong-kong": 38,
  "asia/china/jiangsu": 80,
  "asia/china/macau": 3,
  "asia/china/shanghai": 26,
  "asia/china/tianjin": 15,
  "asia/gcc-states": 254,
  "asia/india/central-zone": 351,
  "asia/india/northern-zone": 223,
  "asia/india/southern-zone": 558,
  "asia/india/western-zone": 220,
  "asia/indonesia/nusa-tenggara": 176,
  "asia/japan/kansai": 352,
  "asia/japan/kanto": 512,
  "asia/jordan": 31,
  "asia/malaysia-singapore-brunei": 251,
  "asia/south-korea": 288,
  "asia/taiwan": 327,
  "asia/thailand": 328,
  "asia/vietnam": 329,
  "central-america/bahamas": 14,
  "europe/austria": 811,
  "europe/czech-republic/praha": 45,
  "europe/czech-republic/stredocesky": 181,
  "europe/czech-republic/ustecky": 112,
  "europe/france/ile-de-france": 339,
  "europe/france/picardie": 133,
  "europe/germany/berlin": 99,
  "europe/germany/brandenburg": 295,
  "europe/greece": 341,
  "europe/ireland-and-northern-ireland": 413,
  "europe/italy/centro": 384,
  "europe/italy/nord-est": 624,
  "europe/italy/nord-ovest": 591,
  "europe/netherlands/flevoland": 35,
  "europe/netherlands/noord-holland": 189,
  "europe/netherlands/utrecht": 99,
  "europe/netherlands/zuid-holland": 211,
  "europe/spain/castilla-la-mancha": 107,
  "europe/spain/cataluna": 270,
  "europe/spain/madrid": 85,
  "europe/turkey": 648,
  "europe/united-kingdom/england": 1697,
  "europe/united-kingdom/scotland": 327,
  "europe/united-kingdom/wales": 148,
  "north-america/mexico": 646,
  "north-america/us/alabama": 150,
  "north-america/us/alaska": 144,
  "north-america/us/arizona": 302,
  "north-america/us/arkansas": 100,
  "north-america/us/california": 1330,
  "north-america/us/colorado": 382,
  "north-america/us/connecticut": 217,
  "north-america/us/delaware": 22,
  "north-america/us/district-of-columbia": 21,
  "north-america/us/florida": 657,
  "north-america/us/georgia": 356,
  "north-america/us/hawaii": 27,
  "north-america/us/idaho": 129,
  "north-america/us/illinois": 360,
  "north-america/us/indiana": 199,
  "north-america/us/iowa": 134,
  "north-america/us/kansas": 116,
  "north-america/us/kentucky": 154,
  "north-america/us/louisiana": 146,
  "north-america/us/maine": 91,
  "north-america/us/maryland": 214,
  "north-america/us/massachusetts": 310,
  "north-america/us/michigan": 314,
  "north-america/us/minnesota": 287,
  "north-america/us/mississippi": 94,
  "north-america/us/missouri": 197,
  "north-america/us/montana": 100,
  "north-america/us/nebraska": 101,
  "north-america/us/nevada": 123,
  "north-america/us/new-hampshire": 72,
  "north-america/us/new-jersey": 164,
  "north-america/us/new-mexico": 136,
  "north-america/us/new-york": 497,
  "north-america/us/north-carolina": 429,
  "north-america/us/north-dakota": 128,
  "north-america/us/ohio": 324,
  "north-america/us/oklahoma": 169,
  "north-america/us/oregon": 254,
  "north-america/us/pennsylvania": 347,
  "north-america/us/puerto-rico": 74,
  "north-america/us/rhode-island": 52,
  "north-america/us/south-carolina": 164,
  "north-america/us/south-dakota": 49,
  "north-america/us/tennessee": 190,
  "north-america/us/texas": 722,
  "north-america/us/us-virgin-islands": 3,
  "north-america/us/utah": 169,
  "north-america/us/vermont": 46,
  "north-america/us/virginia": 428,
  "north-america/us/washington": 364,
  "north-america/us/west-virginia": 99,
  "north-america/us/wisconsin": 293,
  "north-america/us/wyoming": 94,
  "russia/central-fed-district": 878,
  "south-america/brazil/sudeste": 859,
  "south-america/peru": 256
};
