// GENERATED by scripts/ingest/world-regions.mjs from https://download.geofabrik.de/index-v1.json on 2026-09-24.
// Do not edit by hand: change lib/discovery/world-destinations.ts and re-run it.
//
// For each world destination, the Geofabrik files its thirty-mile circle
// reaches, the town's own file first. Every path here had a checksum on
// Geofabrik and answered as a download when this was written.

/** Destination name → Geofabrik region paths, centre first. */
export const WORLD_REGIONS: Readonly<Record<string, readonly string[]>> = {
  "Hong Kong": [
    "asia/china/hong-kong"
  ],
  "Bangkok": [
    "asia/thailand"
  ],
  "London": [
    "europe/united-kingdom/england"
  ],
  "Macau": [
    "asia/china/macau"
  ],
  "Singapore": [
    "asia/malaysia-singapore-brunei"
  ],
  "Paris": [
    "europe/france/ile-de-france",
    "europe/france/picardie"
  ],
  "Dubai": [
    "asia/gcc-states"
  ],
  "New York": [
    "north-america/us/new-york",
    "north-america/us/connecticut",
    "north-america/us/new-jersey"
  ],
  "Kuala Lumpur": [
    "asia/malaysia-singapore-brunei"
  ],
  "Istanbul": [
    "europe/turkey"
  ],
  "Delhi": [
    "asia/india/northern-zone",
    "asia/india/central-zone"
  ],
  "Antalya": [
    "europe/turkey"
  ],
  "Shenzhen": [
    "asia/china/guangdong"
  ],
  "Mumbai": [
    "asia/india/western-zone"
  ],
  "Phuket": [
    "asia/thailand"
  ],
  "Rome": [
    "europe/italy/centro"
  ],
  "Tokyo": [
    "asia/japan/kanto"
  ],
  "Pattaya": [
    "asia/thailand"
  ],
  "Taipei": [
    "asia/taiwan"
  ],
  "Mecca": [
    "asia/gcc-states"
  ],
  "Guangzhou": [
    "asia/china/guangdong"
  ],
  "Prague": [
    "europe/czech-republic/praha",
    "europe/czech-republic/stredocesky",
    "europe/czech-republic/ustecky"
  ],
  "Medina": [
    "asia/gcc-states"
  ],
  "Seoul": [
    "asia/south-korea"
  ],
  "Amsterdam": [
    "europe/netherlands/noord-holland",
    "europe/netherlands/flevoland",
    "europe/netherlands/utrecht",
    "europe/netherlands/zuid-holland"
  ],
  "Agra": [
    "asia/india/central-zone",
    "asia/india/northern-zone"
  ],
  "Miami": [
    "north-america/us/florida"
  ],
  "Osaka": [
    "asia/japan/kansai"
  ],
  "Los Angeles": [
    "north-america/us/california"
  ],
  "Shanghai": [
    "asia/china/shanghai",
    "asia/china/jiangsu"
  ],
  "Ho Chi Minh City": [
    "asia/vietnam"
  ],
  "Denpasar": [
    "asia/indonesia/nusa-tenggara"
  ],
  "Barcelona": [
    "europe/spain/cataluna"
  ],
  "Las Vegas": [
    "north-america/us/nevada"
  ],
  "Milan": [
    "europe/italy/nord-ovest"
  ],
  "Chennai": [
    "asia/india/southern-zone"
  ],
  "Vienna": [
    "europe/austria"
  ],
  "Johor Bahru": [
    "asia/malaysia-singapore-brunei"
  ],
  "Jaipur": [
    "asia/india/northern-zone"
  ],
  "Cancún": [
    "north-america/mexico"
  ],
  "Berlin": [
    "europe/germany/berlin",
    "europe/germany/brandenburg"
  ],
  "Cairo": [
    "africa/egypt"
  ],
  "Athens": [
    "europe/greece"
  ],
  "Orlando": [
    "north-america/us/florida"
  ],
  "Moscow": [
    "russia/central-fed-district"
  ],
  "Venice": [
    "europe/italy/nord-est"
  ],
  "Madrid": [
    "europe/spain/madrid",
    "europe/spain/castilla-la-mancha"
  ],
  "Ha Long": [
    "asia/vietnam"
  ],
  "Riyadh": [
    "asia/gcc-states"
  ],
  "Dublin": [
    "europe/ireland-and-northern-ireland"
  ],
  "Valladolid": [
    "north-america/mexico"
  ],
  "Pisté": [
    "north-america/mexico"
  ],
  "Rio de Janeiro": [
    "south-america/brazil/sudeste"
  ],
  "Beijing": [
    "asia/china/beijing",
    "asia/china/hebei",
    "asia/china/tianjin"
  ],
  "Huairou": [
    "asia/china/beijing",
    "asia/china/hebei"
  ],
  "Aguas Calientes": [
    "south-america/peru"
  ],
  "Cusco": [
    "south-america/peru"
  ],
  "Wadi Musa": [
    "asia/jordan"
  ],
  "Giza": [
    "africa/egypt"
  ]
};

/** Size of each file in megabytes when this was generated, for planning the weekly job. */
export const WORLD_REGION_MB: Readonly<Record<string, number>> = {
  "africa/egypt": 179,
  "asia/china/beijing": 37,
  "asia/china/guangdong": 173,
  "asia/china/hebei": 108,
  "asia/china/hong-kong": 38,
  "asia/china/jiangsu": 80,
  "asia/china/macau": 3,
  "asia/china/shanghai": 26,
  "asia/china/tianjin": 15,
  "asia/gcc-states": 254,
  "asia/india/central-zone": 351,
  "asia/india/northern-zone": 223,
  "asia/india/southern-zone": 558,
  "asia/india/western-zone": 220,
  "asia/indonesia/nusa-tenggara": 176,
  "asia/japan/kansai": 352,
  "asia/japan/kanto": 512,
  "asia/jordan": 31,
  "asia/malaysia-singapore-brunei": 251,
  "asia/south-korea": 288,
  "asia/taiwan": 327,
  "asia/thailand": 328,
  "asia/vietnam": 329,
  "europe/austria": 811,
  "europe/czech-republic/praha": 45,
  "europe/czech-republic/stredocesky": 181,
  "europe/czech-republic/ustecky": 112,
  "europe/france/ile-de-france": 339,
  "europe/france/picardie": 133,
  "europe/germany/berlin": 99,
  "europe/germany/brandenburg": 295,
  "europe/greece": 341,
  "europe/ireland-and-northern-ireland": 413,
  "europe/italy/centro": 384,
  "europe/italy/nord-est": 624,
  "europe/italy/nord-ovest": 591,
  "europe/netherlands/flevoland": 35,
  "europe/netherlands/noord-holland": 189,
  "europe/netherlands/utrecht": 99,
  "europe/netherlands/zuid-holland": 211,
  "europe/spain/castilla-la-mancha": 107,
  "europe/spain/cataluna": 270,
  "europe/spain/madrid": 85,
  "europe/turkey": 648,
  "europe/united-kingdom/england": 1697,
  "north-america/mexico": 646,
  "north-america/us/california": 1330,
  "north-america/us/connecticut": 217,
  "north-america/us/florida": 657,
  "north-america/us/nevada": 123,
  "north-america/us/new-jersey": 164,
  "north-america/us/new-york": 497,
  "russia/central-fed-district": 878,
  "south-america/brazil/sudeste": 859,
  "south-america/peru": 256
};
